spring:
  application:
    name: review-service

  config:
    import: configserver:http://config-server:8888, optional:file:.env[.properties]
# has been changed to eureka server for docker.
  cloud:
    config:
      fail-fast: true
logging:
  level:
    com.skillsync.review.client: DEBUG
    feign: DEBUG