spring:
  application:
    name: auth-service
    
  config:
    import: optional:file:.env[.properties], optional:configserver:http://config-server:8888
    # has been changed to eureka server for docker.