spring:
  application:
    name: api-gateway

  config:
    import: configserver:http://config-server:8888
    # has been changed to config server for docker.

  cloud:
    config:
      fail-fast: true