spring:
  application:
    name: api-gateway

  config:
    import: 
      - optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
      - optional:file:./src/main/resources/application-override.yml

  cloud:
    config:
      fail-fast: true
